### ISSUE TITLE
Mana charge speed on created wand stuck on 2.

### ISSUE THREAD

**Issue by CredibleOpossum** [codefaux/persistence#12]
![image](https://github.com/user-attachments/assets/472840c9-e87b-42a9-9561-30cc93b1f4cb)

Things tried:
- Researching a bunch of wands
- Clearing all save data, validating files.
- Cloning from github, using workshop version.

I would assume this is a datastore issue, but I'm not sure.

**Comment by Tmktahu** [comment]
I have also encountered this issue.

**Comment by CredibleOpossum** [comment]
I can't seem to get old commits to work, so I can't search for when this behavior starts for me.

**Comment by CredibleOpossum** [comment]
2082a4a appears to have the correct behavior, but is clearly a much different version.
