### ISSUE TITLE
[BUG] Search function hotkey interupt

### ISSUE THREAD

**Issue by monbon234** [codefaux/persistence#6]
Whilst using the search bar in the buy spells tab, pressing any hotkeys will still activate them. If the 'I' key (defaultly bound to open inventory) is pressed, without being rebound to a non letter key, it will close the buy spell tab and open the spell inventory, interrupting the search. This means that any words with the letter 'I' cannot be typed in by default.
The space bar also has a similar effect, where if it is pressed whilst using the search bar, it will still cause the player to jump, also closing the buy spell tab.

**Comment by codefaux** [comment]
This issue has been resolved in current and upcoming release, thanks for the report.

The only keys which will impact window status are ` aka grave, tab, and escape. Search functionality has been rewritten, adding both name and description search (prefix #) as well as comma or space separated keywords for AND-style searches, it applies to the Always Casts window, as well as the Research and Purchase windows, and I've a few new sort order options. I'm open to other "fancy search" features, but I'll close this issue.
